
import React, { createContext, useState, useContext, useCallback, useMemo, useEffect } from 'react';

// Define languages and their properties
export type Language = 'en' | 'lt';
export const languages: { code: Language; name: string }[] = [
    { code: 'en', name: 'English' },
    { code: 'lt', name: 'Lietuvių' },
];

// Define translation strings
const translations: Record<Language, Record<string, string>> = {
  en: {
    'common.cancel': 'Cancel',
    'common.save': 'Save Changes',
    'header.title': 'AI Blood Pressure Tracker',
    'header.welcome': 'Welcome, {{userName}}!',
    'header.settingsAriaLabel': 'Open settings',
    'upload.title': 'Add New Reading(s)',
    'upload.dropzone.click': 'Click to upload',
    'upload.dropzone.drag': 'or drag and drop',
    'upload.dropzone.formats': 'PNG, JPG, or WEBP',
    'upload.dropzone.selected': '{{count}} file(s) selected.',
    'upload.button.default': 'Upload Image(s)',
    'upload.button.camera': 'Use Camera',
    'upload.button.processing': 'Processing...',
    'upload.summary': 'Processed {{total}} image(s). {{success}} added. {{failed}} failed.',
    'upload.summary.errorDetails': 'Error Details:',
    'upload.summary.errorItem': '- {{count}} file(s): {{reason}}',
    'readings.title': 'Your Readings',
    'table.date': 'Date',
    'table.systolic': 'Systolic (SYS)',
    'table.diastolic': 'Diastolic (DIA)',
    'table.pulse': 'Pulse',
    'table.empty.filtered': 'No readings match the selected date range.',
    'table.empty.noData': 'No readings yet. Upload an image to get started!',
    'chart.title': 'Blood Pressure Trends',
    'chart.empty.noData': 'A trend chart will be displayed here once you have at least two readings.',
    'chart.empty.filtered': 'No readings match the selected date range.',
    'chart.empty.notEnough': 'Not enough data in the selected date range to display a trend. Select a wider range or add more readings.',
    'analysis.title': 'AI Analysis',
    'analysis.regenerateAriaLabel': 'Regenerate analysis',
    'analysis.empty.notEnough': 'Add at least two readings to generate a trend analysis.',
    'analysis.empty.noAnalysis': 'No analysis available. Click the refresh button to try again.',
    'analysis.keyMetrics': 'Key Metrics (Avg)',
    'analysis.systolic': 'Systolic',
    'analysis.diastolic': 'Diastolic',
    'analysis.pulse': 'Pulse',
    'analysis.overallTrend': 'Overall Trend',
    'analysis.comparison': 'Comparison',
    'analysis.observations': 'Observations',
    'insights.title': 'Health Insights',
    'insights.empty': 'Personalized health tips will appear here once an analysis is generated.',
    'filter.title': 'Date Filter',
    'filter.startDate': 'Start Date',
    'filter.endDate': 'End Date',
    'filter.startDateAriaLabel': 'Filter start date',
    'filter.endDateAriaLabel': 'Filter end date',
    'filter.reset': 'Reset',
    'filter.toggleAriaLabel': 'Toggle date filter visibility',
    'filter.show': 'Show',
    'filter.hide': 'Hide',
    'reports.title': 'Advanced Reports',
    'reports.summaryTitle': 'Health Summary',
    'reports.stat.avg': 'AVERAGE',
    'reports.stat.total': 'TOTAL',
    'reports.stat.highSystolic': 'Highest Systolic',
    'reports.stat.highDiastolic': 'Highest Diastolic',
    'reports.recordedOn': 'Recorded on',
    'reports.timeOfDayTitle': 'Average by Time of Day',
    'reports.time.morning': 'Morning',
    'reports.time.afternoon': 'Afternoon',
    'reports.time.evening': 'Evening',
    'reports.time.night': 'Night',
    'reports.consistencyTitle': 'Logging Consistency',
    'reports.consistencyDesc': 'Percentage of days you logged a reading in the selected period.',
    'export.button': 'Export PDF',
    'export.mainTitle': 'Blood Pressure Report',
    'export.period': 'Report Period',
    'export.periodStart': 'Beginning',
    'export.periodEnd': 'Now',
    'export.periodTo': 'to',
    'export.analysisTitle': 'AI Analysis Summary',
    'export.overallTrend': 'Overall Trend',
    'export.keyMetrics': 'Key Metrics (Average)',
    'export.systolic': 'Systolic',
    'export.diastolic': 'Diastolic',
    'export.pulse': 'Pulse',
    'export.observations': 'Observations',
    'export.insightsTitle': 'Health Insights',
    'export.readingsTitle': 'Detailed Readings',
    'export.modal.title': 'Export Options',
    'export.modal.includeAnalysis': 'Include AI Analysis',
    'export.modal.includeInsights': 'Include Health Insights',
    'export.modal.notAvailable': 'Not available for current selection',
    'settings.title': 'Settings',
    'settings.closeAriaLabel': 'Close settings',
    'settings.profile.title': 'Profile',
    'settings.profile.name': 'Your Name',
    'settings.profile.dob': 'Date of Birth',
    'settings.appearance.title': 'Appearance',
    'settings.appearance.theme': 'Theme',
    'settings.appearance.theme.light': 'Light',
    'settings.appearance.theme.dark': 'Dark',
    'settings.appearance.language': 'Language',
    'settings.goals.title': 'Health Goals',
    'settings.goals.systolic': 'Target Systolic (SYS)',
    'settings.goals.diastolic': 'Target Diastolic (DIA)',
    'settings.data.title': 'Data Management',
    'settings.data.clearButton': 'Clear All Readings',
    'settings.data.clearDescription': 'Permanently deletes all your saved blood pressure readings.',
    'settings.data.clearConfirm': 'Are you sure you want to delete all your readings? This action cannot be undone.',
    'error.title': 'Error',
    'error.closeAriaLabel': 'Close error message',
    'errors.network': 'Network error: Could not connect to the AI service. Please check your internet connection and try again.',
    'errors.modelGenericFail': 'Failed to perform action with the AI model.',
    'errors.modelEmptyResponse': 'AI model returned an empty response.',
    'errors.modelInvalidFormat': 'AI model returned an invalid data format.',
    'errors.modelMissingValues': 'AI could not find required values (SYS, DIA, Pulse).',
    'errors.analysis.emptyResponse': 'AI model returned an empty response for analysis.',
    'errors.analysis.invalidFormat': 'AI model returned an invalid analysis format.',
    'errors.insights.invalidFormat': 'AI model returned an invalid insights format.',
    'errors.unexpectedProcessing': 'An unexpected error occurred during image processing.',
    'errors.unknownExtraction': 'An unknown error occurred during extraction.',
    'errors.unknown': 'An unknown error occurred.',
    'errors.analysisFailed': 'Failed to generate AI analysis: {{message}}',
    'errors.analysisObservationsFailed': 'Could not generate observations due to an error.',
    'errors.analysisEncouragement': 'Please try again. If the problem persists, check your connection.',
    'camera.modal.title': 'Capture Reading',
    'camera.capture_button': 'Take Picture',
    'camera.confirm_button': 'Use Picture',
    'camera.retake_button': 'Retake',
    'camera.close_aria': 'Close camera',
    'camera.error.title': 'Camera Error',
    'camera.error.no_devices': 'No camera devices found.',
    'camera.error.permission_denied': 'Camera access was denied. Please allow camera access in your browser settings to use this feature.',
    'camera.error.generic': 'An unexpected error occurred while accessing the camera.',
    'enum.stable': 'Stable',
    'enum.increasing': 'Increasing',
    'enum.decreasing': 'Decreasing',
    'enum.fluctuating': 'Fluctuating',
    'enum.diet': 'Diet',
    'enum.exercise': 'Exercise',
    'enum.stress_management': 'Stress Management',
    'enum.general': 'General',
    // Additional UI translations
    'table.noReadingsFound': 'No Readings Found',
    'table.bloodPressureHistory': 'Blood Pressure History',
    'table.showingReadings': 'Showing {{start}}-{{end}} of {{total}} readings',
    'table.latestData': 'Latest Data',
    'table.currentTargets': 'Current targets: {{sys}}/{{dia}} mmHg',
    'table.targetLabel': 'Target:',
    'table.dateTime': 'Date & Time',
    'table.bloodPressure': 'Blood Pressure',
    'table.assessment': 'Assessment',
    'table.notes': 'Notes',
    'table.actions': 'Actions',
    'table.edit': 'Edit',
    'table.delete': 'Delete',
    'calendar.header': 'Calendar View',
    'calendar.legend': 'Legend',
    'calendar.hasReadings': 'Has readings',
    'calendar.today': 'Today',
    'pin.title': 'Security Verification',
    'pin.message': 'Enter PIN to continue',
    'pin.enterPin': 'Enter your 4-digit PIN',
    'pin.invalidPin': 'Invalid PIN. Please try again.',
    'pin.helpText': 'Enter the 4-digit PIN to modify records',
    'pin.helpSubtext': 'This helps prevent accidental changes',
    'trends.title': 'Blood Pressure Trends',
    'trends.recentPatterns': 'Recent patterns and changes',
    'trends.systolic': 'Systolic',
    'trends.diastolic': 'Diastolic',
    'trends.pulse': 'Pulse',
    'trends.upperPressure': 'Upper pressure',
    'trends.lowerPressure': 'Lower pressure',
    'trends.heartRate': 'Heart rate',
    'trends.lastReadings': 'Last {{count}} readings',
    'trends.average': 'Avg: {{value}}',
    'trends.bpm': 'BPM',
    'trends.cards': 'Cards',
    'trends.chart': 'Chart',
    'trends.compact': 'Compact',
    'trends.gauge': 'Gauge',
    // Blood Pressure Gauge translations
    'gauge.title': 'Blood Pressure Gauges',
    'gauge.subtitle': 'Medical-style gauge visualization',
    'gauge.noDataTitle': 'No Gauge Data Available',
    'gauge.noDataMessage': 'Add readings to see blood pressure gauges',
    'gauge.reading': 'Reading',
    'gauge.systolicPressure': 'Systolic Pressure',
    'gauge.diastolicPressure': 'Diastolic Pressure',
    'gauge.heartRate': 'Heart Rate',
    'gauge.mmHg': 'mmHg',
    'gauge.bpm': 'BPM',
    'gauge.normal': 'Normal',
    'gauge.elevated': 'Elevated',
    'gauge.high': 'High',
    'gauge.of': 'of',
    // Additional trends translations
    'trends.noDataTitle': 'No Trend Data Available',
    'trends.noDataMessage': 'Add more readings to see blood pressure trends',
    'trends.quickTrends': 'Quick Trends',
    'trends.atGlanceOverview': 'At-a-glance overview',
    'trends.interactiveChart': 'Interactive chart showing your last {{count}} readings',
    'trends.trendAnalysis': 'Blood Pressure Trend Analysis',
    'trends.currentAvg': 'Current Avg',
    'trends.optimalBP': 'Optimal BP',
    'trends.highStage1': 'High Stage 1',
    'trends.highStage2': 'High Stage 2',
    // Button translations
    'buttons.addReading': 'Add Reading',
    'buttons.cameraScan': 'Camera Scan',
    'buttons.aiAnalysis': 'AI Analysis',
    'buttons.healthInsights': 'Health Insights',
    'buttons.analyzing': 'Analyzing...',
    'buttons.loading': 'Loading...',
    'buttons.insights': 'Insights',
    'buttons.tableView': 'Table View',
    'buttons.calendarView': 'Calendar View',
    'buttons.exportPDF': 'Export PDF',
    'buttons.cancel': 'Cancel',
    'buttons.runAnalysis': 'Run Analysis',
    'buttons.generateInsights': 'Generate Insights',
    'buttons.quickActions': 'Quick Actions',
    'buttons.statistics': 'Statistics',
    'buttons.totalReadings': 'Total Readings',
    'buttons.thisPeriod': 'This Period',
    // Additional modal text
    'modals.runAnalysisFirst': 'Run AI Analysis first to generate insights.',
    'modals.securityVerification': 'Security Verification',
    'modals.enterPinToEdit': 'Enter PIN to edit record',
    'modals.enterPinToDelete': 'Enter PIN to delete record',
    // ESH Classification translations
    'esh.title': 'ESH Blood Pressure Classification',
    'esh.subtitle': 'European Society of Hypertension 2023 Guidelines',
    'esh.close': 'Close',
    'esh.importantNotes': 'Important Notes:',
    'esh.notes.categoryRule': 'When systolic and diastolic fall into different categories, the higher risk category applies',
    'esh.notes.adultsOnly': 'These classifications are for adults (≥18 years)',
    'esh.notes.measurement': 'Blood pressure should be measured after 5 minutes of rest in a seated position',
    'esh.notes.consultation': 'Always consult a healthcare professional for diagnosis and treatment decisions',
    'esh.table.category': 'Category',
    'esh.table.systolic': 'Systolic',
    'esh.table.diastolic': 'Diastolic',
    'esh.table.risk': 'Risk',
    'esh.table.description': 'Description',
    'esh.categories.optimal': 'Optimal',
    'esh.categories.normal': 'Normal',
    'esh.categories.highNormal': 'High Normal',
    'esh.categories.grade1HTN': 'Grade 1 HTN',
    'esh.categories.grade2HTN': 'Grade 2 HTN',
    'esh.categories.grade3HTN': 'Grade 3 HTN',
    'esh.categories.crisis': 'Hypertensive Crisis',
    'esh.categories.isolatedSystolic': 'Isolated Systolic HTN',
    'esh.categories.hypotension': 'Hypotension',
    'esh.descriptions.optimal': 'Optimal cardiovascular health',
    'esh.descriptions.normal': 'Normal blood pressure',
    'esh.descriptions.highNormal': 'Prehypertension - lifestyle changes recommended',
    'esh.descriptions.grade1HTN': 'Mild hypertension - medical consultation advised',
    'esh.descriptions.grade2HTN': 'Moderate hypertension - treatment typically required',
    'esh.descriptions.grade3HTN': 'Severe hypertension - urgent medical attention required',
    'esh.descriptions.crisis': 'Medical emergency - call emergency services immediately',
    'esh.descriptions.isolatedSystolic': 'High systolic with normal diastolic - common in older adults',
    'esh.descriptions.hypotension': 'Low blood pressure - evaluation if symptomatic',
    'esh.riskLevels.low': 'Low',
    'esh.riskLevels.moderate': 'Moderate',
    'esh.riskLevels.high': 'High',
    'esh.riskLevels.veryHigh': 'Very High',
    'esh.riskLevels.critical': 'Critical',
    'esh.actionRequired': 'Action Required',
    'esh.emergency': 'Emergency (≥ 220/120 mmHg)',
    'esh.emergencyAction': 'Call emergency services immediately',
    'esh.urgent': 'Urgent (180-219/110-119 mmHg)',
    'esh.urgentAction': 'Seek medical care today',
    'esh.schedule': 'Schedule Appointment (160-179/100-109 mmHg)',
    'esh.scheduleAction': 'Contact healthcare provider soon',
    'esh.consult': 'Consult Doctor (140-159/90-99 mmHg)',
    'esh.consultAction': 'Medical evaluation recommended',
    'esh.colorLegend': 'Color Legend',
    'esh.footer.basedOn': 'Based on: 2023 ESH Guidelines for the management of arterial hypertension',
    'esh.footer.journal': 'European Heart Journal (2023) 44, 3824-3877',
  },
  lt: {
    'common.cancel': 'Atšaukti',
    'common.save': 'Išsaugoti pakeitimus',
    'header.title': 'DI Kraujo Spaudimo Matuoklis',
    'header.welcome': 'Sveiki, {{userName}}!',
    'header.settingsAriaLabel': 'Atidaryti nustatymus',
    'upload.title': 'Pridėti naują įrašą(-us)',
    'upload.dropzone.click': 'Spustelėkite įkelti',
    'upload.dropzone.drag': 'arba nutempkite',
    'upload.dropzone.formats': 'PNG, JPG, arba WEBP',
    'upload.dropzone.selected': 'Pasirinkta failų: {{count}}',
    'upload.button.default': 'Įkelti nuotrauką(-as)',
    'upload.button.camera': 'Naudoti kamerą',
    'upload.button.processing': 'Apdorojama...',
    'upload.summary': 'Apdorota nuotraukų: {{total}}. Pridėta: {{success}}. Nepavyko: {{failed}}.',
    'upload.summary.errorDetails': 'Klaidų detalės:',
    'upload.summary.errorItem': '- {{count}} fail.: {{reason}}',
    'readings.title': 'Jūsų įrašai',
    'table.date': 'Data',
    'table.systolic': 'Sistolinis (SYS)',
    'table.diastolic': 'Diastolinis (DIA)',
    'table.pulse': 'Pulsas',
    'table.empty.filtered': 'Nėra įrašų pasirinktame datų intervale.',
    'table.empty.noData': 'Kol kas nėra įrašų. Įkelkite nuotrauką, kad pradėtumėte!',
    'chart.title': 'Kraujo spaudimo tendencijos',
    'chart.empty.noData': 'Tendencijų diagrama bus rodoma čia, kai turėsite bent du įrašus.',
    'chart.empty.filtered': 'Nėra įrašų pasirinktame datų intervale.',
    'chart.empty.notEnough': 'Nepakanka duomenų pasirinktame datų intervale tendencijai parodyti. Pasirinkite platesnį intervalą arba pridėkite daugiau įrašų.',
    'analysis.title': 'DI Analizė',
    'analysis.regenerateAriaLabel': 'Atnaujinti analizę',
    'analysis.empty.notEnough': 'Pridėkite bent du įrašus, kad sugeneruotumėte tendencijų analizę.',
    'analysis.empty.noAnalysis': 'Analizė negalima. Spustelėkite atnaujinimo mygtuką, kad bandytumėte dar kartą.',
    'analysis.keyMetrics': 'Pagrindiniai rodikliai (vid.)',
    'analysis.systolic': 'Sistolinis',
    'analysis.diastolic': 'Diastolinis',
    'analysis.pulse': 'Pulsas',
    'analysis.overallTrend': 'Bendra tendencija',
    'analysis.comparison': 'Palyginimas',
    'analysis.observations': 'Pastebėjimai',
    'insights.title': 'Sveikatos įžvalgos',
    'insights.empty': 'Asmeniniai sveikatos patarimai atsiras čia, kai bus sugeneruota analizė.',
    'filter.title': 'Datos filtras',
    'filter.startDate': 'Pradžios data',
    'filter.endDate': 'Pabaigos data',
    'filter.startDateAriaLabel': 'Filtruoti pradžios datą',
    'filter.endDateAriaLabel': 'Filtruoti pabaigos datą',
    'filter.reset': 'Atstatyti',
    'filter.toggleAriaLabel': 'Perjungti datos filtro matomumą',
    'filter.show': 'Rodyti',
    'filter.hide': 'Slėpti',
    'reports.title': 'Išplėstinės ataskaitos',
    'reports.summaryTitle': 'Sveikatos suvestinė',
    'reports.stat.avg': 'VIDURKIS',
    'reports.stat.total': 'VISUO',
    'reports.stat.highSystolic': 'Aukščiausias sistolinis',
    'reports.stat.highDiastolic': 'Aukščiausias diastolinis',
    'reports.recordedOn': 'Užregistruota',
    'reports.timeOfDayTitle': 'Vidurkis pagal paros laiką',
    'reports.time.morning': 'Rytas',
    'reports.time.afternoon': 'Popietė',
    'reports.time.evening': 'Vakaras',
    'reports.time.night': 'Naktis',
    'reports.consistencyTitle': 'Registravimo nuoseklumas',
    'reports.consistencyDesc': 'Procentas dienų, kuriomis registravote rodmenis pasirinktame laikotarpyje.',
    'export.button': 'Eksportuoti PDF',
    'export.mainTitle': 'Kraujo Spaudimo Ataskaita',
    'export.period': 'Ataskaitos laikotarpis',
    'export.periodStart': 'Pradžia',
    'export.periodEnd': 'Dabar',
    'export.periodTo': 'iki',
    'export.analysisTitle': 'DI Analizės Santrauka',
    'export.overallTrend': 'Bendra Tendencija',
    'export.keyMetrics': 'Pagrindiniai Rodikliai (Vidurkis)',
    'export.systolic': 'Sistolinis',
    'export.diastolic': 'Diastolinis',
    'export.pulse': 'Pulsas',
    'export.observations': 'Pastebėjimai',
    'export.insightsTitle': 'Sveikatos Įžvalgos',
    'export.readingsTitle': 'Detalus Įrašai',
    'export.modal.title': 'Eksportavimo parinktys',
    'export.modal.includeAnalysis': 'Įtraukti DI analizę',
    'export.modal.includeInsights': 'Įtraukti sveikatos įžvalgas',
    'export.modal.notAvailable': 'Negalima dabartiniam pasirinkimui',
    'settings.title': 'Nustatymai',
    'settings.closeAriaLabel': 'Uždaryti nustatymus',
    'settings.profile.title': 'Profilis',
    'settings.profile.name': 'Jūsų vardas',
    'settings.profile.dob': 'Gimimo data',
    'settings.appearance.title': 'Išvaizda',
    'settings.appearance.theme': 'Tema',
    'settings.appearance.theme.light': 'Šviesi',
    'settings.appearance.theme.dark': 'Tamsi',
    'settings.appearance.language': 'Kalba',
    'settings.goals.title': 'Sveikatos tikslai',
    'settings.goals.systolic': 'Sistolinis tikslas (SYS)',
    'settings.goals.diastolic': 'Diastolinis tikslas (DIA)',
    'settings.data.title': 'Duomenų valdymas',
    'settings.data.clearButton': 'Išvalyti visus įrašus',
    'settings.data.clearDescription': 'Visam laikui ištrina visus jūsų išsaugotus kraujo spaudimo įrašus.',
    'settings.data.clearConfirm': 'Ar tikrai norite ištrinti visus savo įrašus? Šio veiksmo negalima anuliuoti.',
    'error.title': 'Klaida',
    'error.closeAriaLabel': 'Uždaryti klaidos pranešimą',
    'errors.network': 'Tinklo klaida: Nepavyko prisijungti prie DI paslaugos. Patikrinkite interneto ryšį ir bandykite dar kartą.',
    'errors.modelGenericFail': 'Nepavyko atlikti veiksmo su DI modeliu.',
    'errors.modelEmptyResponse': 'DI modelis grąžino tuščią atsakymą.',
    'errors.modelInvalidFormat': 'DI modelis grąžino neteisingą duomenų formatą.',
    'errors.modelMissingValues': 'DI negalėjo rasti būtinų verčių (SYS, DIA, Pulsas).',
    'errors.analysis.emptyResponse': 'DI modelis grąžino tuščią atsakymą analizei.',
    'errors.analysis.invalidFormat': 'DI modelis grąžino neteisingą analizės formatą.',
    'errors.insights.invalidFormat': 'DI modelis grąžino neteisingą įžvalgų formatą.',
    'errors.unexpectedProcessing': 'Apdorojant nuotrauką įvyko netikėta klaida.',
    'errors.unknownExtraction': 'Išgaunant duomenis įvyko nežinoma klaida.',
    'errors.unknown': 'Įvyko nežinoma klaida.',
    'errors.analysisFailed': 'Nepavyko sugeneruoti DI analizės: {{message}}',
    'errors.analysisObservationsFailed': 'Nepavyko sugeneruoti pastebėjimų dėl klaidos.',
    'errors.analysisEncouragement': 'Bandykite dar kartą. Jei problema kartojasi, patikrinkite ryšį.',
    'camera.modal.title': 'Nufotografuoti rodmenį',
    'camera.capture_button': 'Fotografuoti',
    'camera.confirm_button': 'Naudoti nuotrauką',
    'camera.retake_button': 'Fotografuoti iš naujo',
    'camera.close_aria': 'Uždaryti kamerą',
    'camera.error.title': 'Kameros klaida',
    'camera.error.no_devices': 'Nerasta kameros įrenginių.',
    'camera.error.permission_denied': 'Prieiga prie kameros uždrausta. Norėdami naudotis šia funkcija, leiskite prieigą prie kameros naršyklės nustatymuose.',
    'camera.error.generic': 'Bandant pasiekti kamerą įvyko netikėta klaida.',
    'enum.stable': 'Stabili',
    'enum.increasing': 'Didėjanti',
    'enum.decreasing': 'Mažėjanti',
    'enum.fluctuating': 'Svyruojanti',
    'enum.diet': 'Mityba',
    'enum.exercise': 'Pratimai',
    'enum.stress_management': 'Streso valdymas',
    'enum.general': 'Bendra',
    // Additional UI translations
    'table.noReadingsFound': 'Įrašų nerasta',
    'table.bloodPressureHistory': 'Kraujo spaudimo istorija',
    'table.showingReadings': 'Rodoma {{start}}-{{end}} iš {{total}} įrašų',
    'table.latestData': 'Naujausi duomenys',
    'table.currentTargets': 'Dabartiniai tikslai: {{sys}}/{{dia}} mmHg',
    'table.targetLabel': 'Tikslas:',
    'table.dateTime': 'Data ir laikas',
    'table.bloodPressure': 'Kraujo spaudimas',
    'table.assessment': 'Įvertinimas',
    'table.notes': 'Pastabos',
    'table.actions': 'Veiksmai',
    'table.edit': 'Redaguoti',
    'table.delete': 'Ištrinti',
    'calendar.header': 'Kalendoriaus vaizdas',
    'calendar.legend': 'Legenda',
    'calendar.hasReadings': 'Yra įrašų',
    'calendar.today': 'Šiandien',
    'pin.title': 'Saugumo patikrinimas',
    'pin.message': 'Įveskite PIN kodą, kad tęstumėte',
    'pin.enterPin': 'Įveskite savo 4 skaitmenų PIN kodą',
    'pin.invalidPin': 'Neteisingas PIN kodas. Bandykite dar kartą.',
    'pin.helpText': 'Įveskite 4 skaitmenų PIN kodą, kad keistumėte įrašus',
    'pin.helpSubtext': 'Tai padeda išvengti atsitiktinių pakeitimų',
    'trends.title': 'Kraujo spaudimo tendencijos',
    'trends.recentPatterns': 'Paskutiniai šablonai ir pokyčiai',
    'trends.systolic': 'Sistolinis',
    'trends.diastolic': 'Diastolinis',
    'trends.pulse': 'Pulsas',
    'trends.upperPressure': 'Viršutinis spaudimas',
    'trends.lowerPressure': 'Apatinis spaudimas',
    'trends.heartRate': 'Širdies ritmas',
    'trends.lastReadings': 'Paskutiniai {{count}} įrašai',
    'trends.average': 'Vid.: {{value}}',
    'trends.bpm': 'dūžiai/min',
    'trends.cards': 'Kortelės',
    'trends.chart': 'Diagrama',
    'trends.compact': 'Kompaktiškas',
    'trends.gauge': 'Matuoklis',
    // Blood Pressure Gauge translations
    'gauge.title': 'Kraujo spaudimo matuokliai',
    'gauge.subtitle': 'Medicinos stiliaus matuoklių vizualizacija',
    'gauge.noDataTitle': 'Matuoklių duomenų nėra',
    'gauge.noDataMessage': 'Pridėkite įrašų, kad matytumėte kraujo spaudimo matuoklius',
    'gauge.reading': 'Įrašas',
    'gauge.systolicPressure': 'Sistolinis spaudimas',
    'gauge.diastolicPressure': 'Diastolinis spaudimas',
    'gauge.heartRate': 'Širdies ritmas',
    'gauge.mmHg': 'mmHg',
    'gauge.bpm': 'dūžiai/min',
    'gauge.normal': 'Normalus',
    'gauge.elevated': 'Pakilęs',
    'gauge.high': 'Aukštas',
    'gauge.of': 'iš',
    // Additional trends translations
    'trends.noDataTitle': 'Tendencijų duomenų nėra',
    'trends.noDataMessage': 'Pridėkite daugiau įrašų, kad matytumėte kraujo spaudimo tendencijas',
    'trends.quickTrends': 'Greitos tendencijos',
    'trends.atGlanceOverview': 'Greitas apžvalga',
    'trends.interactiveChart': 'Interaktyvus grafikas, rodantis jūsų paskutinius {{count}} įrašus',
    'trends.trendAnalysis': 'Kraujo spaudimo tendencijų analizė',
    'trends.currentAvg': 'Dabartinis vid.',
    'trends.optimalBP': 'Optimalus KS',
    'trends.highStage1': 'Aukštas 1 st.',
    'trends.highStage2': 'Aukštas 2 st.',
    // Button translations
    'buttons.addReading': 'Pridėti įrašą',
    'buttons.cameraScan': 'Kameros skanavimas',
    'buttons.aiAnalysis': 'DI analizė',
    'buttons.healthInsights': 'Sveikatos įžvalgos',
    'buttons.analyzing': 'Analizuojama...',
    'buttons.loading': 'Kraunama...',
    'buttons.insights': 'Įžvalgos',
    'buttons.tableView': 'Lentelės vaizdas',
    'buttons.calendarView': 'Kalendoriaus vaizdas',
    'buttons.exportPDF': 'Eksportuoti PDF',
    'buttons.cancel': 'Atšaukti',
    'buttons.runAnalysis': 'Paleisti analizę',
    'buttons.generateInsights': 'Generuoti įžvalgas',
    'buttons.quickActions': 'Greiti veiksmai',
    'buttons.statistics': 'Statistika',
    'buttons.totalReadings': 'Viso įrašų',
    'buttons.thisPeriod': 'Šis laikotarpis',
    // Additional modal text
    'modals.runAnalysisFirst': 'Pirmiausia paleiskite DI analizę, kad sugeneruotumėte įžvalgas.',
    'modals.securityVerification': 'Saugumo patikrinimas',
    'modals.enterPinToEdit': 'Įveskite PIN kodą, kad redaguotumėte įrašą',
    'modals.enterPinToDelete': 'Įveskite PIN kodą, kad ištrintumėte įrašą',
    // ESH Classification translations
    'esh.title': 'ESH Kraujo Spaudimo Klasifikacija',
    'esh.subtitle': 'Europos Hipertensijos Draugijos 2023 m. Gairės',
    'esh.close': 'Uždaryti',
    'esh.importantNotes': 'Svarbūs Pastabos:',
    'esh.notes.categoryRule': 'Kai sistolinis ir diastolinis spaudimai patenka į skirtingas kategorijas, taikoma aukštesnės rizikos kategorija',
    'esh.notes.adultsOnly': 'Šios klasifikacijos skiriamos suaugusiems (≥18 metų)',
    'esh.notes.measurement': 'Kraujo spaudimas turi būti matuojamas po 5 minučių poilsio sėdint',
    'esh.notes.consultation': 'Visada konsultuokitės su sveikatos priežiūros specialistu dėl diagnozės ir gydymo sprendimų',
    'esh.table.category': 'Kategorija',
    'esh.table.systolic': 'Sistolinis',
    'esh.table.diastolic': 'Diastolinis',
    'esh.table.risk': 'Rizika',
    'esh.table.description': 'Aprašymas',
    'esh.categories.optimal': 'Optimalus',
    'esh.categories.normal': 'Normalus',
    'esh.categories.highNormal': 'Aukštas Normalus',
    'esh.categories.grade1HTN': '1 laipsnio Hipertensija',
    'esh.categories.grade2HTN': '2 laipsnio Hipertensija',
    'esh.categories.grade3HTN': '3 laipsnio Hipertensija',
    'esh.categories.crisis': 'Hipertensijos Krisė',
    'esh.categories.isolatedSystolic': 'Izoliuota Sistolinė Hipertensija',
    'esh.categories.hypotension': 'Hipotensija',
    'esh.descriptions.optimal': 'Optimali širdies ir kraujagyslių sveikata',
    'esh.descriptions.normal': 'Normalus kraujo spaudimas',
    'esh.descriptions.highNormal': 'Prehipertensija - rekomenduojami gyvenimo būdo pakeitimai',
    'esh.descriptions.grade1HTN': 'Švelni hipertensija - rekomenduojama medicinos konsultacija',
    'esh.descriptions.grade2HTN': 'Vidutinė hipertensija - paprastai reikalingas gydymas',
    'esh.descriptions.grade3HTN': 'Smarki hipertensija - reikalingas skubus medicinos pagalbos kreipimasis',
    'esh.descriptions.crisis': 'Medicinos avarinis atvejis - nedelsiant skambinkite greitajai pagalbai',
    'esh.descriptions.isolatedSystolic': 'Aukštas sistolinis su normaliu diastoliniu - dažnas vyresnio amžiaus žmonėms',
    'esh.descriptions.hypotension': 'Žemas kraujo spaudimas - vertinimas, jei yra simptomų',
    'esh.riskLevels.low': 'Žema',
    'esh.riskLevels.moderate': 'Vidutinė',
    'esh.riskLevels.high': 'Aukšta',
    'esh.riskLevels.veryHigh': 'Labai Aukšta',
    'esh.riskLevels.critical': 'Kritinė',
    'esh.actionRequired': 'Reikalingi Veiksmai',
    'esh.emergency': 'Avarinis Atvejis (≥ 220/120 mmHg)',
    'esh.emergencyAction': 'Nedelsiant skambinkite greitajai pagalbai',
    'esh.urgent': 'Skubus (180-219/110-119 mmHg)',
    'esh.urgentAction': 'Šiandien kreipkitės į medicinos pagalbą',
    'esh.schedule': 'Suplanuokite Vizitą (160-179/100-109 mmHg)',
    'esh.scheduleAction': 'Greitai susisiekite su sveikatos priežiūros specialistu',
    'esh.consult': 'Konsultuokitės su Gydytoju (140-159/90-99 mmHg)',
    'esh.consultAction': 'Rekomenduojamas medicinos vertinimas',
    'esh.colorLegend': 'Spalvų Legendos',
    'esh.footer.basedOn': 'Pagrindu: 2023 m. ESH Gairės arterinės hipertensijos valdymui',
    'esh.footer.journal': 'Europos Širdies Žurnalas (2023) 44, 3824-3877',
  }
};

// Helper to get the initial language
const getInitialLanguage = (): Language => {
    const savedLang = localStorage.getItem('app-lang') as Language;
    if (savedLang && languages.some(l => l.code === savedLang)) {
        return savedLang;
    }
    const browserLang = navigator.language.split('-')[0] as Language;
    return languages.some(l => l.code === browserLang) ? browserLang : 'en';
};

// Create the context
interface LocalizationContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string, replacements?: Record<string, string | number>) => string;
    translateEnum: (value: string) => string;
}

const LocalizationContext = createContext<LocalizationContextType | undefined>(undefined);

// Create the provider component
export const LocalizationProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>(getInitialLanguage);

    useEffect(() => {
        localStorage.setItem('app-lang', language);
    }, [language]);

    const setLanguage = (lang: Language) => {
        if (languages.some(l => l.code === lang)) {
            setLanguageState(lang);
        }
    };

    const t = useCallback((key: string, replacements?: Record<string, string | number>): string => {
        let translation = translations[language][key] || translations['en'][key] || key;
        if (replacements) {
            Object.keys(replacements).forEach(placeholder => {
                translation = translation.replace(`{{${placeholder}}}`, String(replacements[placeholder]));
            });
        }
        return translation;
    }, [language]);

    // Special translator for AI-returned enums
    const translateEnum = useCallback((value: string): string => {
        const key = `enum.${value.toLowerCase().replace(/ /g, '_')}`;
        return t(key, {});
    }, [t]);

    const value = useMemo(() => ({ language, setLanguage, t, translateEnum }), [language, t, translateEnum]);

    return (
        <LocalizationContext.Provider value={value}>
            {children}
        </LocalizationContext.Provider>
    );
};

// Custom hook for easy access
export const useLocalization = (): LocalizationContextType => {
    const context = useContext(LocalizationContext);
    if (context === undefined) {
        throw new Error('useLocalization must be used within a LocalizationProvider');
    }
    return context;
};